export enum WordClassName {
    AUTHOR = "author",
    AUTHOR_OPERATOR = "authorOperator",
    CANDIDATE_PRAENOMEN = "candidatePraenomen",
    CANDIDATE_PRAENOMEN_ABBR = "candidatePraenomenAbbr",
    CANDIDATE_SPECIES = "candidateSpecies",
    CANDIDATUS = "candidatus",
    CITATION_OPERATOR = "citationOperator",
    DATE = "date",
    INCERTAE = "incertae",
    INCERTAE_FOLLOWER = "incertaeFollower",
    MONTH = "month",
    OPERATOR = "operator",
    PRAENOMEN = "praenomen",
    PRAENOMEN_ABBR = "praenomenAbbr",
    SPECIES = "species",
    SPECIES_GROUP = "speciesGroup",
    SPECIFIC_OPERATOR = "specificOperator",
    SUBGENERIC_NAME = "subgenericName",
    SUBGENERIC_RANK = "subgenericRank",
    SUBGENUS = "subgenus",
    SUBSPECIFIC_OPERATOR = "subspecificOperator",
    SUBSPECIFIC_RANK = "subspecificRank",
    SUBSPECIES = "subspecies",
    SUPRAGENERIC_RANK = "supragenericRank",
    VERNACULAR = "vernacular",
    YEAR = "year",
}
